### ISSUE TITLE
ttldb init should check for missing config

### ISSUE THREAD

**Issue by AndCycle** [gordonmessmer/courier-pythonfilter#8]
as I install this package in gentoo linux 
the install package on gentoo missing a basic default config, result in failure to init the filter 

I think the hiccup should be caught to remind user about missing module config file which is not mentioned in README

```
Jul 15 15:24:44 courierfilter[2000]: Starting pythonfilter
Jul 15 15:24:44 courierfilter[2000]: Traceback (most recent call last):
Jul 15 15:24:44 courierfilter[2000]: File "/usr/lib/python-exec/python3.12/pythonfilter", line 409, in <module>
Jul 15 15:24:44 courierfilter[2000]: main()
Jul 15 15:24:44 courierfilter[2000]: File "/usr/lib/python-exec/python3.12/pythonfilter", line 390, in main
Jul 15 15:24:44 courierfilter[2000]: filters = load_filters()
Jul 15 15:24:44 courierfilter[2000]: ^^^^^^^^^^^^^^
Jul 15 15:24:44 courierfilter[2000]: File "/usr/lib/python-exec/python3.12/pythonfilter", line 184, in load_filters
Jul 15 15:24:44 courierfilter[2000]: run_init_filter(module, module_name)
Jul 15 15:24:44 courierfilter[2000]: File "/usr/lib/python-exec/python3.12/pythonfilter", line 109, in run_init_filter
Jul 15 15:24:44 courierfilter[2000]: module.init_filter()
Jul 15 15:24:44 courierfilter[2000]: File "/usr/lib/python3.12/site-packages/pythonfilter/auto_whitelist.py", line 40, in init_filter
Jul 15 15:24:44 courierfilter[2000]: _whitelist = ttldb.TtlDb('auto_whitelist', whitelist_ttl, whitelist_purge_interval)
Jul 15 15:24:44 courierfilter[2000]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 15 15:24:44 courierfilter[2000]: File "/usr/lib/python3.12/site-packages/pythonfilter/ttldb.py", line 327, in TtlDb
Jul 15 15:24:44 courierfilter[2000]: dbtype = db_config['type']
Jul 15 15:24:44 courierfilter[2000]: ~~~~~~~~~^^^^^^^^
Jul 15 15:24:44 courierfilter[2000]: KeyError: 'type'
```

**Comment by gordonmessmer** [comment]
@hannob Do you know any reason that the config file would not be included in the Gentoo package?

**Comment by hannob** [comment]
This seems to be a result of some changes in python packaging. See notes about data_files here:
https://setuptools.pypa.io/en/latest/references/keywords.html

Ultimately, python packages should no longer have any files living outside the python packaging directories. (Currently, the gentoo package puts them into site-packages/etc, which is of course not very useful.)

I'm not sure how to handle this with a package that expects a system-wide configuration file. Probably they just need to be installed manually (?). (In my existing live installations, I already had configs from a previous installation, so I didn't notice.) I will fix that for the gentoo package, but I'm not entirely sure what to recommend for courier-pythonfilter itself.

Maybe do the following:
* Make it so courier-pythonfilter works without these config files present, and use default settings if that's the case.
* Mention in the docs that people have to manually put those configs into /etc if they want to make changes.

**Comment by hannob** [comment]
I've now worked around this in Gentoo's ebuild by removing the etc dir from the python module dir, and manually putting the conf files into /etc, see: https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=e729e1f5240fc2e934fe484271ae6cd68af4e3c2
